services:
  soundbored:
    build:
      context: .
    image: soundbored-local:dev
    ports:
      - "127.0.0.1:4001:4000"
    env_file: .env
    volumes:
      - soundbored_data:/app/priv/static/uploads
    # the below can be added for improved security
      - type: tmpfs
        target: /tmp/mix_pubsub
    read_only: true
    environment:
      TMPDIR: /tmp/mix_pubsub
      SECRET_KEY_BASE_FILE: /run/secrets/soundbored_secret_key_base
    secrets:
      - soundbored_secret_key_base

volumes:
  soundbored_data:

secrets:
  soundbored_secret_key_base:
    # this file should contain securely-generated random data (see README.md)
    # and only be readable by root or the user running the docker daemon
    file: ./secret_key_base.txt
