services:
  soundbored:
    image: christom/soundbored:latest
    ports:
      - "0.0.0.0:4000:4000"
    networks:
      - caddy_network
    env_file: .env

  caddy:
    image: caddy:2
    ports:
      - "0.0.0.0:80:80"
      - "0.0.0.0:443:443"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile:ro
      - caddy_data:/data
      - caddy_config:/config
    networks:
      - caddy_network
    depends_on:
      - soundbored
    env_file: .env

networks:
  caddy_network:
    driver: bridge

volumes:
  caddy_data:
  caddy_config: 