import Config

# Note we also include the path to a cache manifest
# containing the digested version of static files. This
# manifest is generated by the `mix assets.deploy` task,
# which you should run after static files are built and
# before starting your production server.
config :soundboard, SoundboardWeb.Endpoint,
  cache_static_manifest: "priv/static/cache_manifest.json"

config :soundboard, Soundboard.Repo,
  database: "/app/priv/db/soundboard_prod.db",
  pool_size: 5

# Ensure the uploads directory exists
config :soundboard,
  uploads_dir: "/app/priv/static/uploads"

config :soundboard,
  env: :prod

# Configure logging for production - enable debug level for voice troubleshooting
config :logger, level: :debug
