import Config

# Note we also include the path to a cache manifest
# containing the digested version of static files. This
# manifest is generated by the `mix assets.deploy` task,
# which you should run after static files are built and
# before starting your production server.
config :soundboard, SoundboardWeb.Endpoint,
  cache_static_manifest: "priv/static/cache_manifest.json"

# Disable Swoosh Local Memory Storage
config :swoosh, local: false

# Configure Swoosh API Client
config :swoosh, api_client: Swoosh.ApiClient.Finch, finch_name: Soundboard.Finch

config :soundboard, Soundboard.Repo,
  database: "/app/priv/static/uploads/soundboard_prod.db",
  pool_size: 5,
  stacktrace: true,
  show_sensitive_data_on_connection_error: true

# Ensure the uploads directory exists
config :soundboard,
  upload_directory: "/app/priv/static/uploads"

config :soundboard,
  env: :prod

# Configure logging for production - enable debug level for voice troubleshooting
config :logger, level: :debug

# Nostrum configuration for voice debugging with optimized audio settings
config :nostrum,
  youtubedl: nil,
  streamlink: nil,
  ffmpeg: "/usr/bin/ffmpeg",
  # Reduce audio buffering for faster playback
  audio_frames_per_burst: 2,  # Reduced from default 10 (40ms instead of 200ms)
  audio_timeout: 5_000  # Reduced from default 20_000ms
